services:
  - type: web
    name: zemicon-landing-price-calculator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py wsgi:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
